### ISSUE TITLE
Cleanup side nav and tools

### ISSUE THREAD

**Issue by hzrd149** [hzrd149/nostrudel#111]
Remove all the "other stuff" from the side menu and add a "More" item that opens the "toolbox" page

![Image](https://github.com/hzrd149/nostrudel/assets/8001706/1630e421-3681-459e-b378-2bdb40645cdd)

The items listed above the "more" item can show the last 3-4 views the user has used and should default to "streams", "channels", and "communities" 

https://www.figma.com/file/aTwfZ87cD0ZjUbnS09JW3u/Untitled?type=design&node-id=0%3A1&mode=design&t=xKUWSAVxGXA9vqwb-1

**Comment by MrZarp** [comment]
any plans for customizable sidebar?

**Comment by hzrd149** [comment]
Probably not, at this point I'm looking at building more of a dashboard that lets users discover content / feeds https://github.com/hzrd149/nostrudel/issues/113 https://w3.do/MhlM_pOw

**Comment by hzrd149** [comment]
Released
