### ISSUE TITLE
"quoting" is broken on nostrudel.ninja using firefox

### ISSUE THREAD

**Issue by Giszmo** [hzrd149/nostrudel#112]
08:34:07.562 Error: 
    Nt router.js:241
    bse index.js:203
    sr index.js:198
    w2 drawer-sub-view-provider.tsx:106
    Hut embedded-note.tsx:23
    React 12
    i post-modal-provider.tsx:20
    o quote-repost-button.tsx:23
    React 26
    w index.js:395
    v index.js:379
    w index.js:395
    Y router.js:1548
    Y router.js:1548
    $ router.js:1639
    pe router.js:1962
    ge router.js:1847
    le router.js:1723
    c drawer-sub-view-provider.tsx:192
    o embedded-note.tsx:30
    v index.js:690
    React 11
react-dom.production.min.js:189:29

**Comment by hzrd149** [comment]
Is this happening on `nostrudel.ninja` or `next.nostrudel.ninja`? I believe this should be fixed in the `next` version

**Comment by Giszmo** [comment]
It's also reproducible on next.

**Comment by hzrd149** [comment]
This should be fixed in the alpha version now

**Comment by Giszmo** [comment]
looks fixed to me.
