### ISSUE TITLE
noStrudel occasionally stops loading recent notes and shows me notes from May 2023 instead

### ISSUE THREAD

**Issue by DeusDenton** [hzrd149/nostrudel#114]
I've seen this bug happen a number of times over the past few months of using noStrudel, with different relays configured and across different browsers (Safari, Chromium).

Sometimes, when scrolling my main feed (not even very far down), noStrudel runs out of recent notes and shows me a handful of specific notes (usually the same ones, I think) from 2023-05-07. I *think* it may be related to scrolling down too fast after a page load (I'm not sure) but in any case once the bug appears it persists across refreshes. `Settings > Database > Clear cache data` fixes it.

Not a huge deal, but thought I'd report it. Awesome work, noStrudel is the best nostr web client by far IMO.
![image](https://github.com/hzrd149/nostrudel/assets/16936001/978e4b04-9afa-4f2f-974a-3e29b7617726)

**Comment by hzrd149** [comment]
The fix for this should be out in the alpha version

**Comment by hzrd149** [comment]
Released
