### ISSUE TITLE
Notifications frequently miss events

### ISSUE THREAD

**Issue by Giszmo** [hzrd149/nostrudel#115]
nevent1qqs8vmp8zqhyltkekyjd3rhzzuw2ptaae5le4dgdun3whaqx7ral4xqpp4mhxue69uhkummn9ekx7mqppamhxue69uhkummnw3ezumt0d5pzqmjxss3dld622uu8q25gywum9qtg4w4cv4064jmg20xsac2aam5nqvzqqqqqqyy9eke9 p-tag mentions me yet it's not showing up in my notifications. I randomly saw it in my feed. Reloading the notifications dosn't help. It's in the feed but not in the notifications.

I also noticed that noStrudel often is late to pick up on events. I get a notification from snort and review my notifications on noStrudel but can't see it (yet).

**Comment by hzrd149** [comment]
I've been noticing a few issues with notifications not updating as quickly as the timeline. although that's not really whats going on here.
Right now there are 5 types of notifications. zaps, reactions, reposts, and replies / mentions
the reposts are any kind 6 and the replies / mentions are any kind 1s. 

The kind 1s can be broken down as follows
- reply ( event has 1+ e tags )
  - reply to other ( event e tag references a note NOT made by the user )
    - These are hidden in the main notifications, but are shown in the "Threads" view
  - reply to user ( this is presumed to be the default )
    - These are shown
- mention ( event not reply )
  - direct mention ( the users pubkey is used in the content )
    - These are show as mentions
  - indirect mention ( users pubkey is not used in content )
    - These are hidden

for the event in question it falls into the indirect mention category so its hidden. that said though its probably worth adding a sub category to that which covers cases where your note is mentioned. or a "quote" reply?

**Comment by hzrd149** [comment]
this should show up in the alpha version now :+1:

**Comment by Giszmo** [comment]
It's still only on "next"?

With "next" I had minor issues bootstrapping. Had to manually add nos.lol to the relays to see stuff load.

**Comment by hzrd149** [comment]
Released in v0.38.0
