### ISSUE TITLE
relay view broken

### ISSUE THREAD

**Issue by psic4t** [hzrd149/nostrudel#12]
Relay view seems to be broken for some relays. They only show a red box with "Something went wrong
padded hex string expected, got unpadded hex of length 63"

The faulty relays seem to be nostr.mom and spore.ws

**Comment by hzrd149** [comment]
do you know what relays show the error? Ive seen it before but I'm having trouble tracking down exactly what relay and how its causing the issue

**Comment by hzrd149** [comment]
Is this still happening for you? if not I'm going to close this issue
I'm fairly certain this was caused by bad relay data getting cached from an older version of noStrudel. although I cant be sure now since I cant seem to reproduce the issue anymore on my end

**Comment by psic4t** [comment]
Yes, it's still happening. Same relays.

**Comment by psic4t** [comment]
After cleaning the cache under Settings/Database the error seems to be gone (strange though). 

I think we can close this.
