### ISSUE TITLE
nsecbunker connection string does not seem to work

### ISSUE THREAD

**Issue by rolznz** [hzrd149/nostrudel#121]
The connection string I got from my nsecbunker does not seem to work:
 bunker://npub18h633swnunmwqhnvjfj28dprl7mk835stceld3gmr33a4dkug34sqdqftc@relay.nsecbunker.com - as far as I know this should be correct?

It seems nostrudel supports tokens too but does not mention it. It'd be cool to show the options similar to what coracle does.

![image](https://github.com/hzrd149/nostrudel/assets/33993199/8df2e50c-def7-4473-85b4-e2b32730cb74)

**Comment by hzrd149** [comment]
another day another format for bunker URLs.
This should be working in the alpha version now though, just had a add a simple parser for when the URI includes an @
Thanks for pointing it out :+1:

**Comment by rolznz** [comment]
Thanks!
