### ISSUE TITLE
Total noStrudel Death !

### ISSUE THREAD

**Issue by GretaFrank** [hzrd149/nostrudel#124]
just so you know it isn't working at all.  neither timeline nor notifications load at all, and also i can't post to a single relay.

this is since last update.  before the update the timeline also didn't load even with page reload, but if i went to notifications then back to timeline it loaded, and i also could post.

now nothing works at all.

the interface loads and that's it. 

no timeline, no notifications, no posting.

**Comment by GretaFrank** [comment]
seems the switch to the whole inbox / outbox relays is what did it ...

hope you can get it fixed ...

**Comment by Giszmo** [comment]
Does your problem persist? Can you check your developer console in the browser (F12)?
