### ISSUE TITLE
Links with excalamation mark are not rendered correctly

### ISSUE THREAD

**Issue by arneschween** [hzrd149/nostrudel#14]
See

nostr:nevent1qqsyuj866m5rrqredjvqytshfv53lc9le9a9qrmmw7euvm8nvynea3qpz4mhxue69uhhyetvv9ujumt0wd68ytnsw43qdul5cr

the link seems to be cut at the exclamation mark, causing a HTTP 403 for the preview. The behaviour is on next.nostrudel.ninja as well as nostrudel.ninja.

![2023-09-15 21_50_44-noStrudel – Mozilla Firefox](https://github.com/hzrd149/nostrudel/assets/5214548/2b1dc9c7-5174-410b-9352-c143b4fc2c02)

**Comment by hzrd149** [comment]
Some of these news websites have the strangest URL formats... either way it should be fixed now in next.nostrudel.ninja. 
Thanks for opening an issue and taking a screenshot :smile:
