### ISSUE TITLE
Database export format should be one line per event

### ISSUE THREAD

**Issue by mleku** [hzrd149/nostrudel#140]
most tools that work with JSON data use the `.jsonl` format, which is line separated JSON - each line is a separate entry

in this case, it's event objects

is there some reason why the export does not put line separators between each event in the export? it's not a worthwhile file size optimization, one character less per event

**Comment by hzrd149** [comment]
This should be fixed in the next version :+1:
next.nostrudel.ninja

**Comment by hzrd149** [comment]
released in v0.39.0
