### ISSUE TITLE
DM decryption should have option to be automatic

### ISSUE THREAD

**Issue by mleku** [hzrd149/nostrudel#141]
i'm building a relay that i've decided to use DMs as a control interface (including a custom workaround for clients without NIP-42) for administering the relay

however, it's a bit clunky to use nostrudel DM interface to test/use it

it would be nice if there was an option to automatically decrypt all DMs or at least a checkbox next to the decrypt all for a specific, open chat

**Comment by hzrd149** [comment]
There should be an option now in "Performance settings" to automatically decrypt DMs in the alpha version

**Comment by mleku** [comment]
alpha meaning https://next.nostrudel.ninja right?

**Comment by hzrd149** [comment]
released in v0.39.0
