### ISSUE TITLE
Unblur more than one image

### ISSUE THREAD

**Issue by Giszmo** [hzrd149/nostrudel#144]
Please allow un-blurring more than one image at a time. If I hit one image in a page, I typically want all images to be un-blurred without having to click a dozen times. As this might not be what all users always want, I think the best approach would be to have two buttons. One with a single :eye: and the other with :eyes: :eyes: . The latter would reveal all images until you navigate somewhere else.

**Comment by hzrd149** [comment]
released in v0.39.0
