### ISSUE TITLE
Custom emoji reactions are displayed as shortcodes when viewed from other clients

### ISSUE THREAD

**Issue by Lokuyow** [hzrd149/nostrudel#165]
**To Reproduce**
1. Custom emoji reactions from noStrudel
![スクリーンショット 2024-04-19 161725](https://github.com/hzrd149/nostrudel/assets/94349922/1056acfc-d3af-400f-8e01-1d3200e854f8)
https://nostrudel.ninja/#/n/nevent1qvzqqqqqqypzpmzzcaj5rzeah8y940ln4z855wa72af4a6aac4zjypql55egcpsqqythwumn8ghj7um9v9exx6pwdehhxtn5dajxz7f0q9n8wumn8ghj7enfd36x2u3wdehhxarj9emkjmn99ah8qatzx9snxurkwajnyupnwcmk6mn20gmxsmr9xcehyd3j8pmkcwthx5mrwcthxa6nyvmx0fchxvpkxfmr2an3vdchzafnwdnksvelvfex7ctyvdshxapaw3e82egqyp0js4q6sclqhhlv0h76yhr58c43vv3fxumppqv8e6wdmhztn5kdj7ezhuu
2. View it from other clients (nostter, amethyst, etc.)
For example: https://nostter.app/nevent1qqs972z5r2rruz7la37lmgjuwslzk93j9ymnvyypsl8fehwufwwjekg2eahhq
3. shortcode is displayed
![スクリーンショット 2024-04-19 161738](https://github.com/hzrd149/nostrudel/assets/94349922/bf47d79d-b188-42bb-b114-87360103f99e)

**speculation**
noStrudel's custom emoji reactions
```
{
  "kind": 7,
  "content": "oikurasats_icon",
...
```
"content": ":oikurasats_icon:",
Isn't it necessary to have :: symbols before and after?

**Comment by hzrd149** [comment]
This is a bug with the current stable version. it is fixed in the `next` version and will be fixed with v0.40.0

**Comment by Lokuyow** [comment]
Thank you!
