### ISSUE TITLE
link previews with long text are not word wrapped

### ISSUE THREAD

**Issue by arneschween** [hzrd149/nostrudel#17]
See note1nryv605h3kjve4kqcctt6d3s604537atlpwd57xdusu3n0ukauqqeq3utu

**Comment by hzrd149** [comment]
good catch, this should now be fixed in the alpha version https://next.nostrudel.ninja/#/n/note1nryv605h3kjve4kqcctt6d3s604537atlpwd57xdusu3n0ukauqqeq3utu

I set it to show only 5 lines instead of the whole description since websites with massive descriptions take up too much space on mobile
