### ISSUE TITLE
Profiles not loading

### ISSUE THREAD

**Issue by Giszmo** [hzrd149/nostrudel#173]
Since at least yesterday, profiles are not automatically loading on next and my timeline looks like this:

![image](https://github.com/hzrd149/nostrudel/assets/96378/04052935-a0c2-4fbd-aab3-6aaaf3ea4f7e)

I see no obviously relevant errors on the console.

Both FF and Chrome on Linux affected.

**Comment by hzrd149** [comment]
should be fixed now. I had to break a few things when I was rebuilding the profile loader :grin:
