### ISSUE TITLE
Upload image button in the writing modal

### ISSUE THREAD

**Issue by gzuuus** [hzrd149/nostrudel#19]
It would be nice to have this button directly in the writing modal so you can upload media without leaving the site. Ideally it would be nice to have a list of different providers to choose from.

**Comment by hzrd149** [comment]
This is coming next release https://next.nostrudel.ninja :)
Although right now its just using nostr.build. I need to do a little more research and support chevereto, satellite.earth CDN, and maybe IPFS?

**Comment by gzuuus** [comment]
IPFS wow, would be nice if it works, webtorrent can be interesting too, i think nostrcheck.me was giving you magnet links when you upload to their provider. I have always thought that nostr and torrents can be something together. 

Just checking the new version! very good, in firefox (librewolf) I had a small glitch when I opened the login window (nip07) and closed it without logging in, then it didn't open again, I had to refresh the page, however in chrome it didn't happen, even if I closed the window it appeared again. In the firefox console "User rejected, ignoring further nostr calls contentScriptNostr.bundle.js:1:23634".

**Comment by hzrd149** [comment]
I always thought IPFS was cool but I'm not sure how long uploaded images would last since your not paying to store the images most node prune your images
Webtorrents would also be cool, but probably only for downloads since I don't think a browser could seed for any meaningful amount of time

**Comment by hzrd149** [comment]
Closing since nostr.build image uploads are implemented and working
