### ISSUE TITLE
ERROR: Cant find NIP-05 ID when freshly added.

### ISSUE THREAD

**Issue by gourcetools** [hzrd149/nostrudel#2]
![image](https://user-images.githubusercontent.com/120996278/227066604-18c13df2-ec8b-48c2-845f-449c2882d6aa.png)

https://gourcetools.github.io/.well-known/nostr.json have been updated and i can't save profile infos with nip-05 if invalid. 
Even tho the feature to verify is really, really nice, i'm not sure you should grey out the save button. It seems like your server did not catch my nip-05, is this done on your side with a cache maybe this is why i can't save?

Just to let you know my user experience...

**Comment by gourcetools** [comment]
Ok, just happened to apply change right after i posted this. It took 10 minutes or so. My point is that if a user just bought a nip for example of just updated his website, he might be trying to update change to his profile less than 10 minutes after he published the nostr.json, so this would be confusing with this very specific situation.

**Comment by hzrd149** [comment]
There is an in memory cache and an indexeddb cache but they only store the successful responses. also the login view is setup to bypass both caches.

It could be the browser caching the request and I could add a flag to the request to tell the browser not to cache it. although im not sure if that would fix the issue.

**Comment by hzrd149** [comment]
closing since the NIP-05 code has changed significantly since march
