### ISSUE TITLE
Feed view for Categorized People List

### ISSUE THREAD

**Issue by gzuuus** [hzrd149/nostrudel#20]
It would be a very interesting feature if the people lists could display the feed composed by the public keys of the list. At the moment listr has something similar, [for example](https://listr.lol/a/naddr1qq94qatjv5s9x6t8deskcq3qjlrs53pkdfjnts29kveljul2sm0actt6n8dxrrzqcersttvcuv3qxpqqqp6nztxm2lu). Also amethyst, where you can choose the source of your feed by "your followers", "global", and other Categorized People Lists from kind30000.

This would allow you to browse feeds curated by you or other users.

Some key features would be to be able to follow these lists so you can access them easily and watch your feed filtered through them, and even to be able to 'fork' other people's lists so that if you find someone else's curated list and want to modify it you can do so easily.

**Comment by hzrd149** [comment]
Already done :smile: although I admit the button is kind of hidden

In the list view there is a "View Feed" button in the upper right https://next.nostrudel.ninja/#/lists/naddr1qqgk6etdv5sxxmmwdehkjumnv46hyuczypl4c26wfzswnlk2vwjxky7dhqjgnaqzqwvdvz3qwz5k3j4grrt46qcyqqq82vqggvgd0

Also there is a star button next to the list name that allows you to "Favorite" it so it shows up as an option in the main home feed

**Comment by hzrd149** [comment]
closing issue since feature is complete
