### ISSUE TITLE
Moving my Nostr data from a compromised nsecKey to a new nsecKey.

### ISSUE THREAD

**Issue by OmniEdge** [hzrd149/nostrudel#205]
With Bitcoin, when i think my keys have been exposed i can simply create a new secKey and transfer everything to my new wallet. 

In case i think my nostr nsecKey might have been exposed how can i move all my nostr data to to my new nsecKey? Is this on client side or protocol side?

**Comment by MrDraxs** [comment]
shouldn't this be marked as closed? since the solution isn't the client responsability?
