### ISSUE TITLE
Default display settings

### ISSUE THREAD

**Issue by 1l0** [hzrd149/nostrudel#209]
![Screenshot 2024-08-27 at 21 56 15](https://github.com/user-attachments/assets/0a8beb01-230a-4295-a173-f35073e55c6e)
This display settings should be default for new users. Trust me.

**Comment by OmniEdge** [comment]
The default setting in `Max Page width` is `none`. This actually shows everything on the page without having to scroll left and right.

**Comment by 1l0** [comment]
My bad for not being more specific. The image above refers to:
Max Page width = Medium
Theme = ChakraUI

Nostrudel is the most advanced client for Nostr, but users' first impressions might be misled by its appearance.
Full width is too much for reading on desktop. ChakraUI looks prettier than the current default.

Besides that, a simpler logo might be better for the masses like this:
![nostrudel_light_green.png](https://raw.githubusercontent.com/1l0/logo/master/nostrudel/nostrudel_light_green.png)
![nostrudel_dark_green.png](https://raw.githubusercontent.com/1l0/logo/master/nostrudel/nostrudel_dark_green.png)
https://github.com/1l0/logo/tree/master/nostrudel

**Comment by 1l0** [comment]
By the way, why not "Nostrudel" instead of "noStrudel"?

**Comment by OmniEdge** [comment]
@1l0 close issue/question?

**Comment by 1l0** [comment]
I do. Thanks for the response.
