### ISSUE TITLE
Make nip-89 client tag opt-in and add popup to enable

### ISSUE THREAD

**Issue by hzrd149** [hzrd149/nostrudel#210]

**Comment by ktecho** [comment]
Hey!

I'm looking at nostrudel events and I see tags like this

```
["client", "noStrudel", "31990:266805e0c9210dfa324c6cba3573b14bee49da4209c9456f9484e5106cd4f8a5:1681066552549"]
```

But looking at the [nip-89 documentation](https://github.com/nostr-protocol/nips/blob/master/89.md), I don't see how they're related. In the nip-89 docs, it seems messages with 31989 and 31990 are sent separately, but you're sending this 31990 tag in events of different kinds. Are this "client" tags defined in another place? Thanks!
