### ISSUE TITLE
Render link previews/embeds at end of note rather than inline

### ISSUE THREAD

**Issue by badonyx** [hzrd149/nostrudel#28]
Inline seems more often than not to disturb the intended flow/appearance of notes.

**Comment by weex** [comment]
Since notes have no styling I like that we can embed content at a certain point. As far as disturbance goes I would propose to be able to turn off link previews.

**Comment by hzrd149** [comment]
Agreed, I've noticed this a few times myself. Adding an option to turn off link previews would be a pretty easy fix. but I think I might tweak the default behavior so it only show link previews for links that are at the end of a sentence or in their own sentence.
That way you still get to see a bunch of previews but It will never cut a sentence in half

**Comment by badonyx** [comment]
Sounds good to me!

**Comment by hzrd149** [comment]
fixed in v0.33.0
