### ISSUE TITLE
can't reply to notifications.

### ISSUE THREAD

**Issue by GretaFrank** [hzrd149/nostrudel#31]
if i go to notifications > replies i can see comments people left for me

but there is no button to reply to any of them

some of the notes are clickable and open a side panel that does have option to reply

but i just ran into an issue where the side panel opened without the particular note i was trying to reply to

i'm sorry if this is a confusing description of the problem but i think it's a pretty major bug

and even on the main timeline when "show replies" is enabled only half the posts can be replied to directly.

so it's kind of a widespread issue that overall in the client only about a third of notes on average can be replied to without jumping through a bunch of hoops.  this is unnecessarily complicated.  i should be able to simply click reply cloud icon on any note but most notes do not have it for no apparent reason other than it being a bug.

**Comment by weex** [comment]
I think this may be due to a connection problem with the relay that supplied that note. If so reloading may help. Also if you post a new note, a screen will come up that shows which relays are timing out. What I'm noticing is that some popular relays drop after a few minutes.

Maybe you can post a screenshot of the relevant part of the relay health screen like:

![image](https://github.com/hzrd149/nostrudel/assets/38776/474b7a93-800b-4d60-8a43-1f332bb0a864)

**Comment by GretaFrank** [comment]
correction: it's actually possible to reply to the note, but only if you click on the time stamp such as "15m" on the upper right corner of the note.  this will open the note in the side panel where you can reply to it.  clicking on the note itself does nothing - you have to click on the time stamp.

i have previously known this but forgot.  sorry.

still, this should be improved.

**Comment by hzrd149** [comment]
I have plans to completely rebuild the notifications view so its simpler and easier to tell whats going on. and also fix this issue where you can see the notifications but cant reply or react to them

Ill log this under better notifications view until I get a chance to revisit it

**Comment by hzrd149** [comment]
Closing this issue since the recent changes to the notifications view give you the ability to reply to notes
