### ISSUE TITLE
Remember position in feed after clicking on a post.

### ISSUE THREAD

**Issue by KruyKaze** [hzrd149/nostrudel#32]
This one is huge for usability.
Whenever you click on a post and then go back to the feed, Nostrudel will go back to the top. 
Thank you!

**Comment by weex** [comment]
This is something a lot of apps struggle with since I don't think they can any particular note is going to be available. It's definitely an expectation that many users have.

**Comment by hzrd149** [comment]
I have a vague Idea how I can fix this but I'm going to need to do a lot more performance optimizations before I can

If you had scrolled past 100+ notes in the main timeline then clicked on a note. When you went back it would have to render all 100+ notes so the timeline would be the same length and you would be at the same position.
Unfortunately rendering 100+ notes makes the browser freeze (its worse on mobile) so Id have to find a way to fix that

**Comment by KruyKaze** [comment]
Right, maybe open the note in a sidebar or something like that?

**Comment by hzrd149** [comment]
This is fixed in the alpha version now

**Comment by KruyKaze** [comment]
Awesome!

**Comment by hzrd149** [comment]
Released
