### ISSUE TITLE
feature request - centered timeline

### ISSUE THREAD

**Issue by GretaFrank** [hzrd149/nostrudel#34]
right now my feed looks like this:

![image](https://github.com/hzrd149/nostrudel/assets/146442815/4869455c-43ea-4d0f-b644-2b4b570a9f50)

in other words left menu pane and right timeline pane are combined first and then centered 

there is unused space on the left and the timeline itself is off to the right

instead the timeline should be centered and the menu should be all the way to the left

i realize this may add some if / then statements or such because if you center the timeline first the menu may or may not fit in the remaining space so sometimes the timeline will be centered perfectly and other times it may be slightly shifted ...

still i don't think anybody cares where the menu is - people are looking at the timeline - so it makes no sense to center anything but the timeline.

**Comment by hzrd149** [comment]
I never noticed this, thanks for bringing it up
This should be fixed in the alpha version now

**Comment by GretaFrank** [comment]
yes it looks better now thanks !
