### ISSUE TITLE
NIP-05 verification for RSS gateway is displaying an exclamation mark

### ISSUE THREAD

**Issue by psic4t** [hzrd149/nostrudel#4]
See this post for instance:

https://nostrudel.ninja/#/n/nevent1qqsv3340guhmqadgxhe8cvshnx304mjtss2r37pn3rvlnu5jrrg7vwspzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqgnwaehxw309aex2mrp09skymr99ehhyecpnksay

NIP-05 verification works für this address: https://atomstr.data.haus/.well-known/nostr.json?name=https://rss.dw.com/atom/rss-de-all

but it still got no checkmark.

**Comment by hzrd149** [comment]
It looks like `https://atomstr.data.haus` dose not have CORS enabled https://cors-test.codehappy.dev/?url=https%3A%2F%2Fatomstr.data.haus%2F.well-known%2Fnostr.json%3Fname%3Dhttps%3A%2F%2Frss.dw.com%2Fatom%2Frss-de-all&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get

Unfortunately there is not much I can do on the client side. the best I can do is try to use something like https://corsproxy.io/ to bypass the CORS restrictions

**Comment by hzrd149** [comment]
https://github.com/hzrd149/nostrudel/commit/70bada5e968ed0cb059e9eaff07240d9e9dc8e24 should fix this issue.

You can test it out here: https://next.nostrudel.ninja/#/n/nevent1qqsv3340guhmqadgxhe8cvshnx304mjtss2r37pn3rvlnu5jrrg7vwspzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqgnwaehxw309aex2mrp09skymr99ehhyecpnksay

**Comment by psic4t** [comment]
I just got home and enabled CORS on the /.well-known route in Atomstr. Do you want to rollback your fix (if using corsproxy) and we try it without the proxy?

**Comment by hzrd149** [comment]
Ill keep the change in, its something that's been on my todo list for a while now and this prompted me to finish it.
To elaborate, https://github.com/hzrd149/nostrudel/commit/70bada5e968ed0cb059e9eaff07240d9e9dc8e24 adds a default CORS proxy, noStrudel already had an option to set a custom CORS proxy but there was no default

The CORS tester looks good now :+1: 
https://cors-test.codehappy.dev/?url=https%3A%2F%2Fatomstr.data.haus%2F.well-known%2Fnostr.json%3Fname%3Dhttps%3A%2F%2Frss.dw.com%2Fatom%2Frss-de-all&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get

**Comment by psic4t** [comment]
Looks great! Thanks a lot for this cool client! I'm using it as my default now!
