### ISSUE TITLE
feature request - require "reason" when using NSFW label

### ISSUE THREAD

**Issue by GretaFrank** [hzrd149/nostrudel#40]
when i mark posts NSFW and forget to include "reason" half of the relays do not accept the post because they need that "reason" field.

but i can't just do it over because the other half of the relays accepted it already and it will now be duplicate.

the correct solution IMO is to REQUIRE the reason field before posting NSFW labeled notes, to ensure that all relays accept the note.

noStrudel doesn't even seem to display the NSFW label when no reason was included, in which case it makes even more sense to REQUIRE the "reason" field is filled out when posting.  otherwise you're giving user the illusion that their post will go through properly but it only posts to half the relays and if it does display it displays without the warning label, which is even worse than the post not going through at all because now everybody will unfollow you ! ! !

**Comment by weex** [comment]
Confirmed. Here's the error I go btw. Thanks to noStrudel for showing the error. Who knows how many NSFW posts are soft-censored in this way by many other apps.

![Screenshot from 2023-10-26 10-44-51](https://github.com/hzrd149/nostrudel/assets/38776/b9441c6c-0a1a-431f-92f3-967b500ac7b5)

**Comment by hzrd149** [comment]
Fixed, the Content warning should show even when the `content-warning` tag doesn't have a reason.
I also made the reason required when making a new post. although this dose not align with [NIP-36](https://github.com/nostr-protocol/nips/blob/master/36.md) which says the reason is optional

The changes are in the Alpha version
