### ISSUE TITLE
amount of replies, repost ||| the like button counting up every click

### ISSUE THREAD

**Issue by fromaaage** [hzrd149/nostrudel#6]
hey :)

please add the option, to show the amount of replies, reposts.

The like button counting up and up if i press like :smile:

**Comment by hzrd149** [comment]
Liking a post multiple times is not a bug, its just the way nostr works :)

As for showing reactions and reposts you can click the small menu on the bottom right of a note to see zaps/reactions

![image](https://github.com/hzrd149/nostrudel/assets/8001706/afad5150-9bc4-403a-a405-fb1738925fed)

This is pretty bad UX and I've got plans rebuilt it so reactions are displayed more prominently

**Comment by fromaaage** [comment]
> This is pretty bad UX and I've got plans rebuilt it so reactions are displayed more prominently

i only need a "number" beside reply or repost. So i know, if there is maybe a funny conversation :D :D :D  for me the ui itself is okay :+1:
