### ISSUE TITLE
certain notes won't display

### ISSUE THREAD

**Issue by psic4t** [hzrd149/nostrudel#7]
No posts of Hacker News Daily RSS feed are visible:

https://nostrudel.ninja/#/u/npub1cfgtutmzspmge05vaxtk5hk5226dt8waf43jprhdzth0twl39s2qyds4yu/notes

but they are in other clients:
https://snort.social/p/npub1cfgtutmzspmge05vaxtk5hk5226dt8waf43jprhdzth0twl39s2qyds4yu
https://primal.net/profile/npub1cfgtutmzspmge05vaxtk5hk5226dt8waf43jprhdzth0twl39s2qyds4yu

Maybe because of the amount of links in each note?

**Comment by hzrd149** [comment]
Its looks like an issue where the client cant find the relays to read from, by default noStrudel reads from these relays https://github.com/hzrd149/nostrudel/blob/master/src/services/client-relays.ts#L13-L19
