### ISSUE TITLE
Keyboard shortcut - ctrl-enter or alt-enter to send a post/reply/dm

### ISSUE THREAD

**Issue by dwebert** [hzrd149/nostrudel#78]
can get a ctrl-enter to send something. 

and maybe in settings the option to activate/deactivate the behavior.

**Comment by dwebert** [comment]
![image](https://github.com/hzrd149/nostrudel/assets/18017148/c020c469-7d1b-4903-8cd7-19bb3f83de43)

**Comment by hzrd149** [comment]
Id rather not add a setting for it, but ill categorize this under general DM improvements.
The DMs views are some of the oldest views in the app and they really need to be cleaned up and made more performant

**Comment by dwebert** [comment]
i am referring not only to DM. More important for posting notes. (and replies)

**Comment by hzrd149** [comment]
ctrl+enter should now be working in the alpha version

**Comment by hzrd149** [comment]
released in v0.37.0
