### ISSUE TITLE
custom reaction available in future releases? :smirk: 

### ISSUE THREAD

**Issue by fromaaage** [hzrd149/nostrudel#8]
https://github.com/hzrd149/nostrudel/blob/46902cdd6f1771cf4bdef64df7c4ce9a67748c03/src/components/note/buttons/reaction-button.tsx#L71C52-L71C52

**Comment by hzrd149** [comment]
that's some old test code, but yes id like to add custom emojis and reactions. I just haven't had the time to figure out the design yet :)

**Comment by hzrd149** [comment]
custom reactions are now available https://nostrudel.ninja/
