### ISSUE TITLE
a bubble or a simple number for drawer/replies to indicate ... "some replies are hiding here"

### ISSUE THREAD

**Issue by dwebert** [hzrd149/nostrudel#80]
and for drawer/replies a bubble or a simple number maybe. or something to indicate ... "some replies are hiding here"

like the 63 before or like a bubble (4)  (2 optiones in the mockup here)

![image](https://github.com/hzrd149/nostrudel/assets/18017148/ca19fece-aa2f-419d-8d53-bc3d4363cab0)

**Comment by hzrd149** [comment]
already have an issue for this feature :) #64
