### ISSUE TITLE
Unify design of buttons highlighted replies/reposts/type-list view

### ISSUE THREAD

**Issue by dwebert** [hzrd149/nostrudel#83]
the green border is fine to highlight. but now also needed for highlight the active "list-view" icon on the right

![image](https://github.com/hzrd149/nostrudel/assets/18017148/d60968ab-f519-465f-84a3-d4796247d3be)

**Comment by dwebert** [comment]
add new reply toggle on the search-page

![image](https://github.com/hzrd149/nostrudel/assets/18017148/5ef4ecea-88a4-4b3a-9b82-826c52640d32)

**Comment by hzrd149** [comment]
fixed in alpha version
