### ISSUE TITLE
Auto-decrypt messages

### ISSUE THREAD

**Issue by Giszmo** [hzrd149/nostrudel#92]
Not sure if it's a bug on my end but messages need one click each to read. That is very annoying and doesn't resolve an issue anybody might have as far as I can think of. I'm using nos2x.

**Comment by Giszmo** [comment]
understood and partly agreed. I'm not happy with giving this permission lightly but would hope to see its use being throttled by the extension and not by the app. I hope that extensions first keep record of what was signed and decrypted on who's request and second also give better control of permissions.

So my extension allows mas-decryption but your app doesn't know this. It can't probe if decrypt works. Decrypt would be async and it could set a 100ms timeout to know that manual interaction was required but can it cancel the request?

**Comment by hzrd149** [comment]
Done, changes should be live in the alpha version

**Comment by dwebert** [comment]
works fine with ff+alby. i think we can close this one
