### ISSUE TITLE
Search relays gets reset when new search is executed

### ISSUE THREAD

**Issue by 0xtrr** [hzrd149/nostrudel#94]
Hi!

If I go to https://nostrudel.ninja/#/search and click the "x Relays" button in the top right corner, add a relay to the search and then execute the search, the relay I've added is automatically deselected and only the 3 default select relays are selected.

**Comment by hzrd149** [comment]
Fixed with 0972691939af7bfd61031d3e9dbffb5ec455cdad in the alpha version

**Comment by hzrd149** [comment]
Released
