### ISSUE TITLE
Option modal on community post seems to cut off too early

### ISSUE THREAD

**Issue by 0xtrr** [hzrd149/nostrudel#95]
The modal popping up in the bottom right corner in the below image seems to be cut off a bit too early? I'm not able to scroll or anything to get more options. This is on the latest "next" docker image.

![ferffrefre](https://github.com/hzrd149/nostrudel/assets/86188777/b0d3bc26-fcab-4dc3-bc12-423c92fa3ac2)

**Comment by hzrd149** [comment]
the fix is in the alpha version
